### PR TITLE
 Pull Request: Hangman Game Enhancements and Fixes

### PR DESCRIPTION
**Pull request by ignabelitzky**
This Pull Request introduces several enhancements and fixes to the Hangman game project. Here's a summary of the changes made:

1. **Makefile Improvements:**
Updated the Makefile to include additional flags for enhanced compilation and linking processes.
Implemented a 'clean' command within the Makefile to facilitate the removal of the executable, promoting a cleaner build process.

2. **Git Ignore Configuration:**
Added a .gitignore file to exclude compiled files, executables, and other non-essential artifacts from version control, improving repository cleanliness and organization.

3. **Enhanced User Input:**
Implemented functionality enabling users to input a word for comparison within the game, enhancing interactivity and customization options.

These changes aim to streamline development processes, improve project maintainability, and enhance the overall user experience. Your feedback and review on these enhancements are greatly appreciated.

### CODE REVIEW

**Comment by mikeTwoTimes** [comment]
Thank you so much for your contribution to my Hangman project! This is my first ever pull request, so I am sorry if it took me a while to address it. Here is my review of your requested changes.

1. Makefile Improvements:
This is my first time seeing the -march flag, but after some research I think it makes perfect sense to have that as a build flag.
The 'clean' command is also a welcome addition to the makefile.

2. Git Ignore Configuration:
The addition of a .gitignore will definitely be useful for when I want to expand upon this project, or if someone else would also like to add their own contribution!

3. Enhanced User Input:
Allowing users to enter both words and letters as input is a great idea, and I can see how it would improve user experience. However I think it is important for the users input to be validated. Input should always be alphabetic, and there should not be repeat inputs either. Adding support for word input makes the issue of input validation more tricky. So I am going to have to respectfully decline this change.

Overall I am very appreciative of your requested changes, and even more so that you found interest in my project. If you have any other additions you would like to make please do not hesitate to do so!

**Comment by ignabelitzky** [comment]
You're welcome! I'm glad you found the contributions helpful. I understand your concerns regarding input validation. If you prefer to maintain strict validation, I respect that decision.

**Comment by ignabelitzky** [comment]
By the way, feel free to check out my implementation of the Hangman Game for Linux over at https://github.com/ignabelitzky/hangman. I'd love to hear your thoughts on it!

**Comment by mikeTwoTimes** [comment]
I actually did take a peek at that earlier, as well as your video to ascii repo. They are both incredible. How long did it take you to get that proficient with ncurses and opencv?

**Comment by ignabelitzky** [comment]
> I actually did take a peek at that earlier, as well as your video to ascii repo. They are both incredible. How long did it take you to get that proficient with ncurses and opencv?

A couple of years, but I worked with those libraries on and off due to the time constraints of other college projects that I didn't make public on GitHub.

**Pull request closed without merging**
